/**
 * 24/7 WHATSAPP AUTO-REPLY BOT FOR RAILWAY
 * Running with Baileys Multi-Device & Terminal QR Code (Zero Meta API Key)
 */

// Node.js crypto module setup - MUST precede all Baileys and Signal imports
const crypto = require('crypto');
if (!global.crypto) {
  global.crypto = crypto;
}
if (!globalThis.crypto) {
  globalThis.crypto = crypto.webcrypto || crypto;
}
if (crypto.webcrypto && !global.crypto.subtle) {
  try {
    global.crypto.subtle = crypto.webcrypto.subtle;
  } catch (e) {}
}

const {
  default: makeWASocket,
  useMultiFileAuthState,
  DisconnectReason,
  Browsers,
  fetchLatestBaileysVersion
} = require('@whiskeysockets/baileys');
const pino = require('pino');
const express = require('express');
const cors = require('cors');
const qrcode = require('qrcode-terminal');
const fs = require('fs');
const path = require('path');

const app = express();
app.use(express.json());
app.use(cors());

// Priority: process.env.PORT provided dynamically by Railway, fallback 3000 (or 8080)
const PORT = process.env.PORT || 3000;
let sock = null;
let currentStatus = 'INITIALIZING';
let latestQrString = null;
let isReconnecting = false;

// Persistent WhatsApp authentication path on Railway Volume (/app/data/auth_info)
function resolveAuthDirectory() {
  if (process.env.AUTH_DIR && process.env.AUTH_DIR.trim()) {
    return path.resolve(process.env.AUTH_DIR.trim());
  }
  // Standard Railway persistent volume mounted at /app/data/auth_info
  const primaryDir = '/app/data/auth_info';
  try {
    if (!fs.existsSync(primaryDir)) {
      fs.mkdirSync(primaryDir, { recursive: true });
    }
    return primaryDir;
  } catch {
    // Local fallback for dev environments
    const fallbackDir = path.resolve(process.cwd(), 'data', 'auth_info');
    if (!fs.existsSync(fallbackDir)) {
      fs.mkdirSync(fallbackDir, { recursive: true });
    }
    return fallbackDir;
  }
}

const AUTH_DIR = resolveAuthDirectory();

// Ensure the auth directory exists without removing or recreating volume data
if (!fs.existsSync(AUTH_DIR)) {
  fs.mkdirSync(AUTH_DIR, { recursive: true });
}

async function startBot() {
  // Clean up any existing socket before opening a fresh connection
  if (sock) {
    try {
      sock.ev.removeAllListeners('connection.update');
      sock.ev.removeAllListeners('creds.update');
      sock.ev.removeAllListeners('messages.upsert');
      sock.end(undefined);
    } catch (e) {}
    sock = null;
  }

  console.log('====================================================');
  console.log('🚀 Initializing WhatsApp Baileys 24/7 Bot on Railway...');
  console.log(`📁 Persistent Auth Directory: ${AUTH_DIR}`);
  console.log('====================================================');

  try {
    // Saves and reuses authentication credentials from /app/data/auth_info
    const { state, saveCreds } = await useMultiFileAuthState(AUTH_DIR);

    // Fetch latest WhatsApp Web version to avoid connection handshake rejections
    const { version, isLatest } = await fetchLatestBaileysVersion().catch(() => ({
      version: [2, 3000, 1015901307],
      isLatest: false
    }));

    if (state.creds?.registered) {
      console.log('🔑 Saved credentials detected. Reconnecting authenticated session...');
    } else {
      console.log('⚡ No active session credentials found. Generating QR code for login...');
    }

    // Initialize Baileys socket using canonical Ubuntu/Chrome browser identity
    sock = makeWASocket({
      version,
      auth: state,
      printQRInTerminal: false,
      logger: pino({ level: 'silent' }),
      browser: Browsers?.ubuntu ? Browsers.ubuntu('Chrome') : ['Ubuntu', 'Chrome', '20.0.04'],
      syncFullHistory: false,
      connectTimeoutMs: 60000,
      defaultQueryTimeoutMs: 60000,
      keepAliveIntervalMs: 10000,
      markOnlineOnConnect: false
    });

    sock.ev.on('creds.update', saveCreds);

    // Connection update listener
    sock.ev.on('connection.update', (update) => {
      const { connection, lastDisconnect, qr } = update;

      // 1. Fresh QR code generated by Baileys
      if (qr) {
        latestQrString = qr;
        currentStatus = 'SCAN_QR_REQUIRED';

        console.log('========== WHATSAPP QR LOGIN ==========');
        console.log('Open WhatsApp → Linked Devices → Link a device');
        console.log('Scan the QR below:');
        qrcode.generate(qr, { small: true });
      }

      // 2. Connection closed / disconnected handling
      if (connection === 'close') {
        const statusCode = lastDisconnect?.error?.output?.statusCode;
        const errorMessage = lastDisconnect?.error?.message || '';
        const isLoggedOut = statusCode === DisconnectReason.loggedOut || statusCode === 401;

        console.log(`⚠️ Connection closed. Status code: ${statusCode || 'unknown'}, reason: ${errorMessage || 'none'}`);

        if (isLoggedOut) {
          currentStatus = 'LOGGED_OUT';
          latestQrString = null;
          console.log('❌ WhatsApp Session was logged out from phone or server.');
          console.log('⚡ A fresh QR code will be generated for new authentication.');
          
          setTimeout(() => {
            startBot();
          }, 3000);
        } else if (statusCode === DisconnectReason.restartRequired || statusCode === 515) {
          console.log('🔄 Baileys restart required (handshake transition). Reconnecting...');
          setTimeout(() => {
            startBot();
          }, 1500);
        } else {
          currentStatus = 'RECONNECTING';
          console.log('🔄 Temporary network drop. Reconnecting 24/7 daemon in 4 seconds...');
          if (!isReconnecting) {
            isReconnecting = true;
            setTimeout(() => {
              isReconnecting = false;
              startBot();
            }, 4000);
          }
        }
      } else if (connection === 'open') {
        currentStatus = 'CONNECTED';
        latestQrString = null;
        console.log('WHATSAPP CONNECTED SUCCESSFULLY');
        console.log(`Device JID: ${sock.user?.id || 'Connected'}`);
        console.log(`Storage: ${AUTH_DIR}`);
      }
    });

    // Automated 24/7 Customer Auto-Reply
    sock.ev.on('messages.upsert', async ({ messages, type }) => {
      if (type !== 'notify') return;
      const msg = messages[0];
      if (!msg || !msg.message || msg.key.fromMe) return;

      const from = msg.key.remoteJid;
      const name = msg.pushName || 'Grahak';
      const text = (
        msg.message.conversation ||
        msg.message.extendedTextMessage?.text ||
        ''
      ).trim();

      if (!text) return;

      console.log(`[Incoming WhatsApp] From: ${name} (${from}): "${text}"`);
      const lower = text.toLowerCase();

      try {
        if (lower === 'hi' || lower === 'hello' || lower === 'namaste' || lower === 'start' || lower === 'rate') {
          await sock.sendMessage(from, {
            text: `Namaste ${name} ji! 🙏 Apex Wholesale & Retail mein aapka swagat hai.\n\nYeh hamara 24/7 WhatsApp Automated Desk hai.\n\nKripya option chunein:\n1️⃣ Product Catalog & Rates\n2️⃣ Latest Bulk Offers\n3️⃣ Talk to Human Executive`
          });
        } else if (lower === '1' || lower.includes('catalog') || lower.includes('price')) {
          await sock.sendMessage(from, {
            text: `Ye lijiye hamari Catalog 📦:\n• Wireless Earbuds: ₹599 (Bulk ₹420)\n• Smartwatch Ultra: ₹1,299 (Bulk ₹950)\n• Fast Charger 65W: ₹499 (Bulk ₹310)\n• Bluetooth Soundbar: ₹1,899 (Bulk ₹1,400)\n\nOrder lagane ke liye product ka naam type karein!`
          });
        } else if (lower === '2' || lower.includes('bulk') || lower.includes('offer')) {
          await sock.sendMessage(from, {
            text: `🔥 *Special Wholesale Bulk Offers:*\n\n• Flat 25% OFF on 20+ units\n• Free shipping on orders above ₹10,000\n• Same-day dispatch with GST invoice\n\nReply with your required quantity to get an instant quote!`
          });
        } else if (lower === '3' || lower.includes('talk') || lower.includes('agent')) {
          await sock.sendMessage(from, {
            text: `Hamare Sales Manager ko notify kar diya gaya hai. Thodi der me aapse baat karenge.`
          });
        }
      } catch (err) {
        console.error('[Auto-Reply Error]:', err);
      }
    });
  } catch (err) {
    console.error('Fatal error starting WhatsApp Bot:', err);
    setTimeout(startBot, 5000);
  }
}

// Health check endpoint for Railway and external uptime monitors
app.get('/', (req, res) => {
  res.json({
    status: 'ok',
    service: 'DirectConnect WhatsApp 24/7 Bot',
    connection: currentStatus,
    authDir: AUTH_DIR,
    timestamp: new Date().toISOString()
  });
});

app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    whatsapp: currentStatus,
    hasActiveSocket: !!sock,
    uptimeSeconds: Math.floor(process.uptime())
  });
});

app.get('/api/health', (req, res) => {
  res.json({
    success: true,
    backend: 'ONLINE',
    whatsappEngine: currentStatus,
    authDirectory: AUTH_DIR,
    timestamp: new Date().toISOString()
  });
});

// Start Express server on 0.0.0.0 and PORT
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server listening on 0.0.0.0:${PORT}`);
  startBot();
});
